#@TYPE: Machine
#@NAME: ultra96-zynqmp
#@DESCRIPTION: Machine support for Ultra96 Evaluation Board.
#

SOC_FAMILY = "zynqmp"
SOC_VARIANT = "eg"

require conf/machine/include/tune-zynqmp.inc
require conf/machine/include/machine-xilinx-overrides.inc
require conf/machine/include/machine-xilinx-default.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-dev"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-xlnx"

UBOOT_MACHINE = "xilinx_zynqmp_zcu100_revC_config"
SPL_BINARY = "spl/boot.bin"

PMU_FIRMWARE_DEPLOY_DIR = "${TOPDIR}/pmutmp/deploy/images/zynqmp-pmu"
PMU_FIRMWARE_IMAGE_NAME = "pmu-firmware-zynqmp-pmu"

SERIAL_CONSOLES = "115200;ttyPS0"

EXTRA_IMAGEDEPENDS += " \
    arm-trusted-firmware \
    virtual/boot-bin \
    virtual/bootloader \
"

IMAGE_BOOT_FILES += " \
    uEnv.txt \
    atf-uboot.ub \
"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS = "kernel-image kernel-devicetree"

MACHINE_FEATURES = "ext2 ext3 vfat usbhost wifi"
